#!/usr/bin/env python3
"""Small, dependency-free helpers for input provenance.

The SFINCS model directory contains useful fixtures generated by the demo
builder.  Those files are deliberately not treated as observations by this
module.  A file is operationally real only when a provenance manifest marks it
as ``real`` and the recorded checksum still matches the file on disk.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


STATUSES = {"real", "assumed", "missing"}
SYNTHETIC_CLASSES = {"synthetic", "generated", "demo", "fixture"}


def sha256_file(path: str | Path) -> str:
    """Return the SHA-256 checksum of *path* without loading it all at once."""

    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def iso_timestamp(value: Any) -> str:
    """Parse a timestamp and return a canonical UTC ISO-8601 value.

    Naive values are interpreted as UTC.  This is intentional: a forcing file
    without a timezone is not allowed to silently acquire the host timezone.
    """

    if not isinstance(value, str) or not value.strip():
        raise ValueError("timestamp must be a non-empty string")
    text = value.strip().replace("Z", "+00:00")
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        for fmt in ("%Y%m%d %H%M%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M"):
            try:
                parsed = datetime.strptime(value.strip(), fmt)
                break
            except ValueError:
                continue
        else:
            raise ValueError(f"invalid timestamp: {value!r}") from None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")


def load_manifest(path: str | Path | None) -> dict[str, Any]:
    """Load and validate a provenance manifest.

    The accepted format is a JSON object with an ``inputs`` object.  Keeping
    this format intentionally small makes it reviewable and usable without a
    GIS or YAML dependency.
    """

    if path is None:
        return {"version": 1, "inputs": {}}
    manifest_path = Path(path)
    with manifest_path.open("r", encoding="utf-8") as stream:
        manifest = json.load(stream)
    if not isinstance(manifest, dict) or not isinstance(manifest.get("inputs"), dict):
        raise ValueError("provenance manifest must contain an object named 'inputs'")
    if manifest.get("version", 1) != 1:
        raise ValueError("unsupported provenance manifest version")
    for name, entry in manifest["inputs"].items():
        if not isinstance(name, str) or not isinstance(entry, dict):
            raise ValueError("manifest inputs must map names to objects")
        status = entry.get("status", "assumed")
        classification = entry.get("provenance_class", entry.get("classification", ""))
        if status not in STATUSES and status != "synthetic":
            raise ValueError(f"invalid status for {name}: {status!r}")
        if status == "synthetic" or str(classification).lower() in SYNTHETIC_CLASSES:
            # Keep the public status vocabulary stable while preserving the
            # important fact that this is generated data.
            entry["status"] = "assumed"
            entry["provenance_class"] = "synthetic"
        checksum = entry.get("checksum_sha256")
        if checksum is not None and (
            not isinstance(checksum, str) or len(checksum) != 64 or any(c not in "0123456789abcdefABCDEF" for c in checksum)
        ):
            raise ValueError(f"invalid checksum for {name}")
    manifest["_path"] = str(manifest_path.resolve())
    return manifest


def manifest_entry(manifest: dict[str, Any], name: str) -> dict[str, Any]:
    """Return a copy of a named entry, or an empty entry when unlisted."""

    entry = manifest.get("inputs", {}).get(name, {})
    return dict(entry) if isinstance(entry, dict) else {}


def resolve_manifest_path(manifest: dict[str, Any], value: str | Path) -> Path:
    """Resolve a manifest-relative path while accepting absolute paths."""

    candidate = Path(value)
    if candidate.is_absolute():
        return candidate
    manifest_path = manifest.get("_path")
    if manifest_path:
        return Path(manifest_path).parent / candidate
    return candidate


def provenance_result(
    *,
    path: Path | None,
    entry: dict[str, Any],
    metadata: dict[str, Any] | None = None,
    error: str | None = None,
) -> dict[str, Any]:
    """Build the common report shape for one input."""

    metadata = metadata or {}
    exists = path is not None and path.is_file()
    expected = entry.get("checksum_sha256")
    actual = None
    checksum_ok = False
    if exists:
        actual = sha256_file(path)
        checksum_ok = expected is not None and actual.lower() == str(expected).lower()
    status = "missing" if not exists else entry.get("status", "assumed")
    if status == "synthetic":
        status = "assumed"
    return {
        "status": status if status in STATUSES else "assumed",
        "valid": bool(exists and not error),
        "operationally_valid": bool(exists and status == "real" and not error and checksum_ok),
        "path": str(path) if path is not None else None,
        "source": entry.get("source", "unprovenanced local file" if exists else None),
        "provenance_class": entry.get("provenance_class", entry.get("classification", "unknown" if exists else None)),
        "checksum_sha256": actual,
        "expected_checksum_sha256": expected,
        "checksum_verified": checksum_ok,
        "crs": metadata.get("crs", entry.get("crs")),
        "vertical_datum": metadata.get("vertical_datum", entry.get("vertical_datum")),
        "timestamp_coverage": metadata.get("timestamp_coverage", {
            "start": entry.get("timestamp_start"),
            "end": entry.get("timestamp_end"),
        }),
        "error": error,
    }
