import os
import json
from pathlib import Path
from typing import Optional, Dict, Any, Union
from app.schemas.sfincs import SFINCSMetadata, SFINCSForcing, SFINCSOutputsCatalog

class SFINCSOutputParser:
    """
    Parser for SFINCS hydrodynamic model simulation outputs produced by P1's pipeline.
    Reads metadata.json, flood_extent.geojson, and registers raster artifacts.
    """

    def __init__(self, base_outputs_dir: Union[str, Path] = "outputs"):
        self.base_outputs_dir = Path(base_outputs_dir)

    def resolve_directory(self, target_dir: Optional[Union[str, Path]] = None) -> Path:
        """
        Resolves the output directory, falling back to common locations if needed.
        """
        if target_dir:
            p = Path(target_dir)
            if p.exists() and p.is_dir():
                return p
        
        # Check primary output directory
        if self.base_outputs_dir.exists():
            return self.base_outputs_dir

        # Try relative paths
        alt_paths = [
            Path("outputs"),
            Path("ml/sfincs/mangaluru/simulations/baseline/outputs"),
            Path("../outputs"),
            Path("../../outputs"),
        ]
        for alt in alt_paths:
            if alt.exists():
                return alt

        raise FileNotFoundError(f"SFINCS output directory not found at {self.base_outputs_dir}")

    def parse_metadata(self, directory: Optional[Union[str, Path]] = None) -> SFINCSMetadata:
        """
        Parses metadata.json generated by SFINCS extraction script.
        """
        output_dir = self.resolve_directory(directory)
        metadata_file = output_dir / "metadata.json"

        if not metadata_file.exists():
            raise FileNotFoundError(f"metadata.json not found in {output_dir}")

        with open(metadata_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        forcing_data = data.get("forcing")
        forcing = None
        if forcing_data:
            forcing = SFINCSForcing(
                rainfall_source=forcing_data.get("rainfall_source"),
                tide_source=forcing_data.get("tide_source"),
            )

        return SFINCSMetadata(
            model=data.get("model", "SFINCS"),
            model_version=data.get("model_version", "v2.4.2"),
            location=data.get("location", "Mangaluru Coastal"),
            event_name=data.get("event_name"),
            simulation_id=data.get("simulation_id", "mangaluru-simulation"),
            start_time=data["start_time"],
            end_time=data["end_time"],
            time_step_minutes=data.get("time_step_minutes", 5),
            grid_resolution_m=data.get("grid_resolution_m", 50),
            crs=data.get("crs", "EPSG:32643"),
            vertical_datum=data.get("vertical_datum", "MSL"),
            max_depth_m=float(data["max_depth_m"]),
            mean_flooded_depth_m=float(data["mean_flooded_depth_m"]) if data.get("mean_flooded_depth_m") is not None else None,
            flooded_area_km2=float(data["flooded_area_km2"]) if data.get("flooded_area_km2") is not None else None,
            onset_threshold_m=float(data.get("onset_threshold_m", 0.05)),
            flood_threshold_m=float(data.get("flood_threshold_m", 0.10)),
            forcing=forcing,
        )

    def parse_flood_extent_geojson(self, directory: Optional[Union[str, Path]] = None) -> Optional[Dict[str, Any]]:
        """
        Loads flood_extent.geojson vector file exported from SFINCS depth rasters.
        Returns the GeoJSON dictionary, or None if not present.
        """
        output_dir = self.resolve_directory(directory)
        geojson_file = output_dir / "flood_extent.geojson"

        if not geojson_file.exists():
            return None

        with open(geojson_file, "r", encoding="utf-8") as f:
            return json.load(f)

    def extract_primary_geometry(self, geojson_data: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """
        Extracts a single Geometry (Polygon or MultiPolygon) from a GeoJSON object or FeatureCollection.
        """
        if not geojson_data:
            return None

        geom_type = geojson_data.get("type")
        if geom_type in ("Polygon", "MultiPolygon", "Point", "LineString"):
            return geojson_data

        if geom_type == "Feature":
            return geojson_data.get("geometry")

        if geom_type == "FeatureCollection":
            features = geojson_data.get("features", [])
            if not features:
                return None
            if len(features) == 1:
                return features[0].get("geometry")
            # If multiple polygons, construct a MultiPolygon
            polygons = []
            for feat in features:
                geom = feat.get("geometry")
                if not geom:
                    continue
                if geom.get("type") == "Polygon":
                    polygons.append(geom.get("coordinates"))
                elif geom.get("type") == "MultiPolygon":
                    polygons.extend(geom.get("coordinates"))
            if polygons:
                return {
                    "type": "MultiPolygon",
                    "coordinates": polygons,
                }

        return None

    def catalog_outputs(self, directory: Optional[Union[str, Path]] = None) -> SFINCSOutputsCatalog:
        """
        Catalogs all available SFINCS deliverables in the given directory.
        """
        output_dir = self.resolve_directory(directory)
        metadata = self.parse_metadata(output_dir)

        def _check_file(name: str) -> Optional[str]:
            p = output_dir / name
            return str(p) if p.exists() else None

        return SFINCSOutputsCatalog(
            simulation_id=metadata.simulation_id,
            metadata=metadata,
            flood_extent_geojson_path=_check_file("flood_extent.geojson"),
            flood_depth_tif_path=_check_file("flood_depth.tif"),
            peak_depth_tif_path=_check_file("peak_depth.tif"),
            onset_time_tif_path=_check_file("onset_time.tif"),
            peak_time_tif_path=_check_file("peak_time.tif"),
        )
